// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: gen1.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfFastScreenBoard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalWidthmm *int32    `protobuf:"varint,1,req,name=totalWidthmm" json:"totalWidthmm,omitempty"`
	Mm2Px        *int32    `protobuf:"varint,2,req,name=mm2px" json:"mm2px,omitempty"`
	TotalWave    *int32    `protobuf:"varint,3,req,name=totalWave" json:"totalWave,omitempty"`
	Row          *int32    `protobuf:"varint,4,req,name=row" json:"row,omitempty"`
	Func         *string   `protobuf:"bytes,5,req,name=func" json:"func,omitempty"`
	Wave         []float64 `protobuf:"fixed64,6,rep,name=wave" json:"wave,omitempty"`
	Instense     []float64 `protobuf:"fixed64,7,rep,name=instense" json:"instense,omitempty"`
}

func (x *InfFastScreenBoard) Reset() {
	*x = InfFastScreenBoard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gen1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfFastScreenBoard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfFastScreenBoard) ProtoMessage() {}

func (x *InfFastScreenBoard) ProtoReflect() protoreflect.Message {
	mi := &file_gen1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfFastScreenBoard.ProtoReflect.Descriptor instead.
func (*InfFastScreenBoard) Descriptor() ([]byte, []int) {
	return file_gen1_proto_rawDescGZIP(), []int{0}
}

func (x *InfFastScreenBoard) GetTotalWidthmm() int32 {
	if x != nil && x.TotalWidthmm != nil {
		return *x.TotalWidthmm
	}
	return 0
}

func (x *InfFastScreenBoard) GetMm2Px() int32 {
	if x != nil && x.Mm2Px != nil {
		return *x.Mm2Px
	}
	return 0
}

func (x *InfFastScreenBoard) GetTotalWave() int32 {
	if x != nil && x.TotalWave != nil {
		return *x.TotalWave
	}
	return 0
}

func (x *InfFastScreenBoard) GetRow() int32 {
	if x != nil && x.Row != nil {
		return *x.Row
	}
	return 0
}

func (x *InfFastScreenBoard) GetFunc() string {
	if x != nil && x.Func != nil {
		return *x.Func
	}
	return ""
}

func (x *InfFastScreenBoard) GetWave() []float64 {
	if x != nil {
		return x.Wave
	}
	return nil
}

func (x *InfFastScreenBoard) GetInstense() []float64 {
	if x != nil {
		return x.Instense
	}
	return nil
}

var File_gen1_proto protoreflect.FileDescriptor

var file_gen1_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc2, 0x01, 0x0a,
	0x12, 0x49, 0x6e, 0x66, 0x46, 0x61, 0x73, 0x74, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x42, 0x6f,
	0x61, 0x72, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x57, 0x69, 0x64, 0x74,
	0x68, 0x6d, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x57, 0x69, 0x64, 0x74, 0x68, 0x6d, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6d, 0x32, 0x70, 0x78,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6d, 0x32, 0x70, 0x78, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x57, 0x61, 0x76, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05,
	0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x57, 0x61, 0x76, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72,
	0x6f, 0x77, 0x18, 0x04, 0x20, 0x02, 0x28, 0x05, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x75, 0x6e, 0x63, 0x18, 0x05, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x66, 0x75, 0x6e,
	0x63, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x61, 0x76, 0x65, 0x18, 0x06, 0x20, 0x03, 0x28, 0x01, 0x52,
	0x04, 0x77, 0x61, 0x76, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x65, 0x6e, 0x73,
	0x65, 0x18, 0x07, 0x20, 0x03, 0x28, 0x01, 0x52, 0x08, 0x69, 0x6e, 0x73, 0x74, 0x65, 0x6e, 0x73,
	0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x6d, 0x61, 0x69, 0x6e,
}

var (
	file_gen1_proto_rawDescOnce sync.Once
	file_gen1_proto_rawDescData = file_gen1_proto_rawDesc
)

func file_gen1_proto_rawDescGZIP() []byte {
	file_gen1_proto_rawDescOnce.Do(func() {
		file_gen1_proto_rawDescData = protoimpl.X.CompressGZIP(file_gen1_proto_rawDescData)
	})
	return file_gen1_proto_rawDescData
}

var file_gen1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gen1_proto_goTypes = []interface{}{
	(*InfFastScreenBoard)(nil), // 0: InfFastScreenBoard
}
var file_gen1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gen1_proto_init() }
func file_gen1_proto_init() {
	if File_gen1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gen1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfFastScreenBoard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gen1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gen1_proto_goTypes,
		DependencyIndexes: file_gen1_proto_depIdxs,
		MessageInfos:      file_gen1_proto_msgTypes,
	}.Build()
	File_gen1_proto = out.File
	file_gen1_proto_rawDesc = nil
	file_gen1_proto_goTypes = nil
	file_gen1_proto_depIdxs = nil
}
